### ISSUE TITLE
Sugestão de alterações do Readme.md para configuração do atalho .desktop

### ISSUE THREAD

**Issue by joaohortsenado** [fabianonunes/openfortivpn.saml.docker#1]
Na configuração do atalho .desktop eu me deparei com a situação em que mesmo salvando o arquivo no local correto ele não aparecia na lista de apps. 

Existe um arquivo que verifica a configuração de arquivos de atalho .desktop.

`desktop-file-validate *.desktop`

rodando no arquivo em questão, ele me apontou um erro em relação à linha de configuração SingleMainWindow, solicitando que fosse incluído o "X-" antes, ficando "X-SingleMainWindow". 

Feito isso, verifiquei que o Exec, pelo menos no meu caso precisava do "sudo" no comando, não sei se foi algo específico do meu ambiente ou não, mas o próprio ubuntu me exibia esse erro. Após isso, ainda solicitou que eu clicasse com o botão direito e selecionasse a opção "allow lauching" no menu de contexto do arquivo .desktop

Enfim, não sei se tudo isso é relativo só ao meu ambiente, mas pode ser o caso de deixar uma observação.

**Comment by fabianonunes** [comment]
Opa, valeu pela investigação!!! Vou adicionar o prefixo ao `SingleMainWindow`.

Ubuntu 18, né? Eu já tinha visto acontecer com um colega, mas eu subi uma VM e não consegui reproduzir.

Quanto ao `sudo`, acho que é melhor não colocar no `Exec` porque o svpn sobe uma sessão de browser para entrada das credenciais e não é uma boa ideia rodar um navegador com permissão de root. O ideal é que a senha do sudo seja informada diretamente no Vte (aquele terminal que vai embeddado), pois assim só o openfortivpn sobe com permissão.

**Comment by joaohortsenado** [comment]
Então, em relação ao comando sudo, mesmo colando no exec, ele solicita a senha.

Por enquanto, ainda estou tentando decifrar o que ocorre com o [domínio  ](https://suporte.interlegis.leg.br/), por algum motivo só retorna ERR_ADDRESS_UNREACHABLE quando estou na vpn.
